# Generated by Django 2.0.13 on 2019-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetail',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
